apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "cluster-overview-experience"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: production
    public_ip: 54.166.80.29
  annotations:
    backstage.io/kubernetes-id: "cluster-overview-experience"
    github.com/project-slug: overview-demo/cluster-overview-experience
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$54.166.80.29 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$54.166.80.29:~/.kube/config ~/.kube/config-cluster-overview-experience\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"54.166.80.29\")' -i ~/.kube/config-cluster-overview-experience\n  export KUBECONFIG=~/.kube/config-cluster-overview-experience\n  kubectl get pods -A\n"
    veecode/cluster-name: cluster-overview-experience
    kubernetes.io/secret-name: cluster-overview-experience-secret
    kubernetes.io/secret-namespace: vkpr
    kubernetes.io/auth-provider: custom
    kubernetes.io/api-server: https://54.166.80.29:6550
    kubernetes.io/api-server-certificate-authority: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekV4TVRZeApOVEV5TURCYUZ3MDBNekV4TVRZeE5URXlNREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNXlTVHJHRjJ3NXJRT0VCRXVKQ0lPRHg2a2ttK0xNZ0Y4OS85T0QwTGlTNFRQMGEzUgpVaXRWUDN1c0EvYnU4SnpuREdzQUNONWZ5UzdmQWx2N0pyUUpCOXdoOFM1aXlOT2pVUUFTN0ozUVVKNVNBT0dwCjlXMXJSQjNuRTZxc0NqRCszM1VGUnJienZPZVBaYVdUMWh1WlNmb3hHYUhxSzJEY09vQjQxaS8xZ3VXcGk1aEgKc3ZPV085K0QrZThaMHBnNm9oV2g2N0hDY0d5WVNXdlNBOEhlS1hndktkMUEralFRdFQ2RWN4ZmxXZVh5WG5tUwpTa0tOZWNKdCtMN3IwcGt6Ull0cXkvanVacFk1cGZiVkpoSk9BU3hzSlMwaVZCWjFBeG9KaGw2Wit4TFNvSWEwCmFVL0VkWHVLdzg2eXkyTWpKdU9OUEFFZWVlU1RFV3ZRbGZFcEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJHRldqZW5BbmZob0RrMTdvUQpHSjZzMzRhdjJqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFzVXFJbTFyc25BTFBmd25pemNkWHN5NU9iL21JCmR1aCt5S3cyZnJtejBDdVRmMzM0VmdsSWNhUEU0ZkZURm1hRG9tSUh6TmExS3hjUWhtUkxDK2RnaDZ5TVAyTzMKOGJ1M0VhN2dpQTVGRllxOFhaTG1EYzhoOGo3RWx1Q2Evd29NeWpSRFpBM2xUNjN3bFBYVzFIQ0pvQmVHZWJGYgp3dGxOb3lJZmhvcndBVjBJSm5qaVN1Vy9YK2h0Qi94TUdYcUJxS2t4WGwzZm45YkEyaXJUUUFVN3ZvZDJpV004ClBvMEg2eVgrS0YwTHErQTRCL0Y3a0QzcXZIeXAzNDRXd2lvUU9PSkQwQUJSMVU2eERxRmVacTEvR250dzVhSnMKMGpOUjBpY0RMajYrL2FScGQ2b0UvM0VWOHZjT29mcUp6TEtzYzMyV1B5OEVDT1FTZ3M3WnJtT2t5dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    kubernetes.io/skip-tls-verify: "false"
    kubernetes.io/skip-metrics-lookup: "false"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
